%YAML 1.1
---
# Suricata configuration file

# Network interface to monitor
af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes

# Rule management
default-rule-path: /etc/suricata/rules
rule-files:
  - tor.rules

# Log directory
default-log-dir: /var/log/suricata

# Correct logging config
outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            payload: yes
            http: yes
            tls: yes

# NFQ (if you're using it — though your Docker CMD suggests af-packet is used)
nfq:
  mode: accept
  repeat-mark: 1
  repeat-mask: 1
  fail-open: yes
  queues:
    - queue: 0

