version: '3.8'

services:
  censor1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: censor1
    privileged: true
    network_mode: host
    tty: true
    volumes:
      - ./censor1:/censor
    working_dir: /censor
  client:
    image: handsonsecurity/seed-ubuntu:large
    container_name: client-10.1.2.1
    volumes:
      - ./client:/client
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.2.1

  relay1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay1-10.1.0.2
    volumes:
      - ./relay1:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.2

  relay2:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay2-10.1.0.3
    volumes:
      - ./relay2:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.3

  relay3:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay3-10.1.0.4
    volumes:
      - ./relay3:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.4

  relay4:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay4-10.1.0.5
    volumes:
      - ./relay4:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.5

  relay5:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay5-10.1.0.6
    volumes:
      - ./relay5:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.6

  relay6:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay6-10.1.0.7
    volumes:
      - ./relay6:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.0.7

  exit_node1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node1-10.1.1.1
    volumes:
      - ./exit1:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.1.1

  exit_node2:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node2-10.1.1.2
    volumes:
      - ./exit2:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.1.2

  exit_node3:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node3-10.1.1.3
    volumes:
      - ./exit3:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.1.3

  hidden_service:
    image: handsonsecurity/seed-ubuntu:large
    container_name: hidden_service-10.1.2.2
    volumes:
      - ./hidden_service:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.1.2.2

networks:
  tor_net:
    name: tor_net-10.1.0.0
    ipam:
      config:
        - subnet: 10.1.0.0/16


