services:
  client:
    image: handsonsecurity/seed-ubuntu:large
    container_name: client-10.1.2.1
    volumes:
      - ./client:/client
    tty: true
    entrypoint: ["/client/entrypoint.sh"]
    command: ["/bin/sh"]
    networks:
      client_net:
        ipv4_address: 10.10.1.10
    cap_add:
      - NET_ADMIN
      - NET_RAW

  relay1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay1-10.10.3.2
    volumes:
      - ./relay1:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.2

  relay2:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay2-10.10.3.3
    volumes:
      - ./relay2:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.3

  relay3:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay3-10.10.3.4
    volumes:
      - ./relay3:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.4

  relay4:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay4-10.10.3.5
    volumes:
      - ./relay4:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.5

  relay5:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay5-10.10.3.6
    volumes:
      - ./relay5:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.6

  relay6:
    image: handsonsecurity/seed-ubuntu:large
    container_name: relay6-10.10.3.7
    volumes:
      - ./relay6:/relay
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.7

  exit_node1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node1-10.10.3.8
    volumes:
      - ./exit1:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.8

  exit_node2:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node2-10.10.3.9
    volumes:
      - ./exit2:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.9

  exit_node3:
    image: handsonsecurity/seed-ubuntu:large
    container_name: exit_node3-10.10.3.10
    volumes:
      - ./exit3:/relay
      - ./hidden_service/certs:/relay/certs/hidden_service
    tty: true
    networks:
      tor_net:
        ipv4_address: 10.10.3.10

  hidden_service:
    image: handsonsecurity/seed-ubuntu:large
    container_name: hidden_service
    volumes:
      - ./hidden_service:/relay
    tty: true
    networks:
      service_net:
        ipv4_address: 10.10.2.20

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    command: ["-i", "eth0", "-i", "eth1"]
    volumes:
      - ./suricata/config:/etc/suricata
      - ./suricata/logs:/var/log/suricata
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      client_net:
        ipv4_address: 10.10.1.2
      service_net:
        ipv4_address: 10.10.2.2


networks:
  client_net:
    ipam:
      config:
        - subnet: 10.10.1.0/24

  service_net:
    ipam:
      config:
        - subnet: 10.10.2.0/24

  tor_net:
    name: tor_net
    ipam:
      config:
        - subnet: 10.10.3.0/24


