version: '3.8'

networks:
  country_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  global_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      country_net:
        ipv4_address: 172.18.0.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - tor-proxy

  firewall:
    build:
      context: .
      dockerfile: firewall/Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      country_net:
        ipv4_address: 172.18.0.254
      global_net:
        ipv4_address: 172.19.0.254

  tor-proxy:
    build:
      context: ./tor-proxy
    networks:
      country_net:
        ipv4_address: 172.18.0.20
      global_net:
        ipv4_address: 172.19.0.20
    cap_add:
      - NET_ADMIN
      - NET_RAW

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    networks:
      global_net:
        ipv4_address: 172.19.0.30
    cap_add:
      - NET_ADMIN
      - NET_RAW