networks:
  censored_net:  # Client network (country)
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1

  tor_net:       # Tor network
    ipam:
      config:
        - subnet: 172.18.2.0/24
          gateway: 172.18.2.1

  global_net:    # External services
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      censored_net:
        ipv4_address: 172.18.1.10

  firewall:
    build:
      context: .
      dockerfile: firewall/Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      censored_net:
        ipv4_address: 172.18.1.100  # Changed from .254
      global_net:
        ipv4_address: 172.19.0.100  # Changed from .254

  tor-proxy:
    build:
      context: ./tor-proxy
    networks:
      censored_net:
        ipv4_address: 172.18.1.20
      tor_net:
        ipv4_address: 172.18.2.20
    cap_add:
      - NET_ADMIN
      - NET_RAW

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    networks:
      global_net:
        ipv4_address: 172.19.0.30
    cap_add:
      - NET_ADMIN
      - NET_RAW

  hidden-service:
    build:
      context: ./tor-hidden
    networks:
      tor_net:
        ipv4_address: 172.18.2.30
      global_net:
        ipv4_address: 172.19.0.40  # Changed from 172.19.0.30 to avoid conflict
    cap_add:
      - NET_ADMIN
      - NET_RAW


  suricata:
      image: jasonish/suricata:latest
      networks:
        censored_net:
          ipv4_address: 172.18.1.200 
      volumes:
        - ./suricata/config:/etc/suricata
        - ./suricata/logs:/var/log/suricata
      cap_add:
        - NET_ADMIN
        - NET_RAW
        - SYS_NICE
      environment:
        - INTERFACE=eth0
      command: ["-i", "eth0", "-c", "/etc/suricata/suricata.yaml", "-S", "/etc/suricata/rules/tor.rules"]
      depends_on:
        - firewall
      restart: unless-stopped
